name: Daily PLAYERS Update

on:
  schedule:
    - cron: '16 22 * * *'
jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '18' 

    - name: Install dependencies
      run: npm install  

    - name: Run the script
      run: node app/githubActions/players.mjs
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
